baseURL = 'https://17xande.dev/'
languageCode = 'en-za'
title = '17xande.dev'

[module]
[[module.imports]]
  path = 'github.com/LordMathis/hugo-theme-nightfall'

[params]
user = "alex"
hostname = "17xande.dev"
published = false
readingTime = false
sitedescription = 'Your website description'
# footerHtml = 'CC-0, Built with <a href="https://gohugo.io" class="footerLink">Hugo</a> and <a href="https://github.com/LordMathis/hugo-theme-nightfall" class="footerLink">Nightfall</a> theme'

  [params.author]
    name = "17XANDE.DEV"
    email = "17xande@gmail.com"

  [params.styles]
    color = "orange"

[[params.social]]
key = 0
name = "github"
url = "https://github.com/17xande"
icon = "fa-brands fa-github"  # Add link to your icon font to `layouts/partials/custom-head.html`
target = "_blank" # Defines your target option in a-href. _blank for a new Tab for example.
aria = "GitHub Profile" # Define the aria label for accessibility like page reader - this is better for your SEO

[[params.social]]
key = 1
name = "twitter"
url = "https://www.example.com"
rel = "me"

[[params.social]]
key = 3
name = "email"
url = "mailto:email@example.com"

[menu]
  [[menu.header]]
    name = "about"
    weight = 0
    url = "/about"

  [[menu.header]]
    name = "contact"
    weight = 0
    url = "/contact"

